# Generated by Django 2.2 on 2019-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_Num', models.CharField(max_length=50)),
                ('node_IP', models.CharField(max_length=50)),
                ('node_MAC', models.CharField(max_length=50)),
                ('node_Power', models.CharField(max_length=50)),
            ],
        ),
    ]
