# Generated by Django 2.2 on 2019-09-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='node_Status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
