# Generated by Django 2.2 on 2019-09-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_manage', '0002_nodeinfo_node_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='node_Type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
